### ISSUE TITLE
ImportError tenacity.asyncio

### ISSUE THREAD

**Issue by vogre** [jd/tenacity#471] opened 2024-06-17 08:11 UTC
Using Python 3.11, and latest tenacity 8.4.0

```
> import tenacity
...
lib/python3.11/site-packages/tenacity/__init__.py", line 653, in <module>
     from tenacity.asyncio import AsyncRetrying  # noqa:E402,I100
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 ModuleNotFoundError: No module named 'tenacity.asyncio'
```

**Comment by GabLinares** [comment] 2024-06-17 08:12
Facing the same issue, seems to be related to a change made in a [recent PR](https://github.com/jd/tenacity/pull/451)

**Comment by Peelz** [comment] 2024-06-17 08:17
Also getting this error, fixed by update requirements.txt `tenacity>=8.2.3,<8.4.0`

**Comment by dpinol** [comment] 2024-06-17 08:19
Strange that CI didn't catch it right?

**Comment by pmercier** [comment] 2024-06-17 08:21
Same here with python 3.12.
What is strange is that asyncio is present in the zip and tar.gz package, but abscent when installed with pip or poetry.
![image](https://github.com/jd/tenacity/assets/584193/c3fc1f78-eec6-45c2-b0b4-0ef7b8b26d50)
![image](https://github.com/jd/tenacity/assets/584193/a823dfd6-7180-4d36-9ee1-87cea32ae285)

**Comment by JeromeDuboisVizzia** [comment] 2024-06-17 08:29
Hey same error here in a AWS lambda using python 3.12, I didn't encounter it last week :-/
```
[ERROR] Runtime.ImportModuleError: Unable to import module 'app': No module named 'tenacity.asyncio'
Traceback (most recent call last):
```
Thanks @Peelz for the workaround

**Comment by harupy** [comment] 2024-06-17 08:37
Encountered the same issue. It looks like the `asyncio` module is missing:

```
% zipinfo -1 ~/Downloads/tenacity-8.4.0-py3-none-any.whl
tenacity/__init__.py
tenacity/_utils.py
tenacity/after.py
tenacity/before.py
tenacity/before_sleep.py
tenacity/nap.py
tenacity/py.typed
tenacity/retry.py
tenacity/stop.py
tenacity/tornadoweb.py
tenacity/wait.py
tenacity-8.4.0.dist-info/LICENSE
tenacity-8.4.0.dist-info/METADATA
tenacity-8.4.0.dist-info/WHEEL
tenacity-8.4.0.dist-info/top_level.txt
tenacity-8.4.0.dist-info/RECORD
```

**Comment by JeromeDuboisVizzia** [comment] 2024-06-17 08:40
> tenacity>=8.2.3,<8.4.0

yes, comparing with a previous version (8.3.0), _asyncio.py is missing in the tenacity folder :/

**Comment by Stefanhg** [comment] 2024-06-17 08:47
In __init__ the import was change to
`from . import asyncio as tasyncio`
It was changed in #451

**Comment by Tenzer** [comment] 2024-06-17 08:59
The problem is with this line:
https://github.com/jd/tenacity/blob/702014bc224240c1bb92bdaab250bda178fd938f/setup.cfg#L26

It isn't recursive so doesn't pick up the `tenacity.asyncio` package.

The fix is to either specify both packages manually:
```
packages =
    tenacity
    tenacity.asyncio
```

or to let setuptools find the packages itself:
```
packages = find:
```

**Comment by cdce8p** [comment] 2024-06-17 09:00
> The problem is with this line:
> 
> https://github.com/jd/tenacity/blob/702014bc224240c1bb92bdaab250bda178fd938f/setup.cfg#L26

Exactly. Opened #474 with a fix.

**Comment by wencan** [comment] 2024-06-17 09:40
This bug prevents llama_index.core from functioning properly.

**Comment by kennethpgreen** [comment] 2024-06-17 09:44
Hey @jd - see you're working on the fix here: https://github.com/jd/tenacity/pull/474. Is it possible to pull the 8.4.0 version in the meantime?

**Comment by edgarrmondragon** [comment] 2024-06-17 10:06
> Hey @jd - see that there's a fix going here: #474. Is it possible to remove the 8.4.0 version in the meantime?

Yeah, 8.4.0 should definitely be yanked.

**Comment by kennethpgreen** [comment] 2024-06-17 10:14
Or @sileht ?

**Comment by sewcio543** [comment] 2024-06-17 11:45
Adding **MANIFEST.in** in root with:
`recursive-include tenacity *
`
would solve the issue as well

**Closed** 2024-06-17 12:00 UTC
