### ISSUE TITLE
Broken install:  "ImportError: No module named 'tasks'"

### ISSUE THREAD

**Issue by mixmastamyk** [jd/tenacity#90] opened 2017-09-28 20:22 UTC
- Py 3.5
- Ubuntu Zesty

```
⏵ sudo -H pip3 install --upgrade tenacity
Collecting tenacity
  Using cached tenacity-4.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/pbr/core.py", line 111, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "/usr/local/lib/python3.5/dist-packages/pbr/util.py", line 267, in cfg_to_args
        wrap_commands(kwargs)
      File "/usr/local/lib/python3.5/dist-packages/pbr/util.py", line 569, in wrap_commands
        cmdclass = ep.resolve()
      File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2322, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
    ImportError: No module named 'tasks'
    error in setup command: Error parsing /tmp/pip-build-_zmuo5av/tenacity/setup.cfg: ImportError: No module named 'tasks'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-_zmuo5av/tenacity/
```

**Comment by mixmastamyk** [comment] 2017-09-28 20:25
Is it related to/caused by pbr?  Not sure.

**Comment by mixmastamyk** [comment] 2017-09-28 20:30
```
⏵ sudo -H pip3.5 install tenacity==4.3.0
Collecting tenacity==4.3.0
  Downloading tenacity-4.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/pbr/core.py", line 111, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "/usr/local/lib/python3.5/dist-packages/pbr/util.py", line 267, in cfg_to_args
        wrap_commands(kwargs)
      File "/usr/local/lib/python3.5/dist-packages/pbr/util.py", line 569, in wrap_commands
        cmdclass = ep.resolve()
      File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2322, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
    ImportError: No module named 'tasks'
    error in setup command: Error parsing /tmp/pip-build-j9qpdm5q/tenacity/setup.cfg: ImportError: No module named 'tasks'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-j9qpdm5q/tenacity/
⏵ sudo -H pip3.5 install tenacity==4.2.0
Collecting tenacity==4.2.0
  Downloading tenacity-4.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/pbr/core.py", line 111, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "/usr/local/lib/python3.5/dist-packages/pbr/util.py", line 267, in cfg_to_args
        wrap_commands(kwargs)
      File "/usr/local/lib/python3.5/dist-packages/pbr/util.py", line 569, in wrap_commands
        cmdclass = ep.resolve()
      File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2322, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
    ImportError: No module named 'tasks'
    error in setup command: Error parsing /tmp/pip-build-8311e7zx/tenacity/setup.cfg: ImportError: No module named 'tasks'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-8311e7zx/tenacity/
🗁  ~/Desktop⏵ sudo -H pip3.5 install tenacity==4.1.0
Collecting tenacity==4.1.0
  Downloading tenacity-4.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/pbr/core.py", line 111, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "/usr/local/lib/python3.5/dist-packages/pbr/util.py", line 267, in cfg_to_args
        wrap_commands(kwargs)
      File "/usr/local/lib/python3.5/dist-packages/pbr/util.py", line 569, in wrap_commands
        cmdclass = ep.resolve()
      File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2322, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
    ImportError: No module named 'tasks'
    error in setup command: Error parsing /tmp/pip-build-0occznm2/tenacity/setup.cfg: ImportError: No module named 'tasks'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-0occznm2/tenacity/
```

**Comment by mixmastamyk** [comment] 2017-09-28 20:38
I don't see any "tasks" in setup.cfg.

**Comment by jd** [comment] 2017-09-28 21:47
Duplicate of https://github.com/jd/tenacity/issues/85

**Closed by jd** 2017-09-28 21:47 UTC
