### ISSUE TITLE
SyntaxError for Python 2.7

### ISSUE THREAD

**Issue by erny** [jd/tenacity#128] opened 2018-07-20 14:10 UTC
When running buildout with this requirement I get SyntaxErrors:

    yield from ...

May be this could be converted to:

    for bar in foo:
        yield bar

?

**Comment by jd** [comment] 2018-07-20 15:53
duplicate of https://github.com/jd/tenacity/issues/88 and I don't think there's anything we can do about this.

**Closed by jd** 2018-07-20 15:53 UTC
Labels: duplicate
